name: Docker

on:
  push:
    branches:
      - master
    tags: ["*"]

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Build and push
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/librechef
          on-master: dev
          tag-pattern: /^([a-z\-_0-9]+)$/
          latest-on-tag: true
          restrict-to: openzim/librechef
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
